// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, first_name, last_name, verify_token)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, first_name, last_name, email, password_hash, verified, verify_token
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	VerifyToken  pgtype.Text `json:"verify_token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.VerifyToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerifyToken,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password_hash, verified, verify_token FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerifyToken,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, first_name, last_name, email, password_hash, verified, verify_token FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerifyToken,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users SET verified = true, verify_token = NULL
WHERE verify_token = $1
RETURNING id, first_name, last_name, email, password_hash, verified, verify_token
`

func (q *Queries) VerifyUser(ctx context.Context, verifyToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, verifyUser, verifyToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerifyToken,
	)
	return i, err
}
