// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int32       `json:"id"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Verified     bool        `json:"verified"`
	VerifyToken  pgtype.Text `json:"verify_token"`
}
